---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---



```{r readandprep}
act <- read.csv(unzip("activity.zip"))
act$date = as.Date(act$date)
act$workday = as.factor(ifelse(weekdays(act$date) %in% c("Saturday","Sunday"), "Weekend", "Weekday"))
str(act)
summary(act)
head(act[act$interval==1200,],10)
```

## What is mean total number of steps taken per day?
```{r PA1plots}
meansbydate = tapply(act$steps, as.factor(act$date), mean, na.rm=TRUE)
mediansbydate = tapply(act$steps, as.factor(act$date), median, na.rm=TRUE)
sumbydate = tapply(act$steps, as.factor(act$date), sum, na.rm=TRUE)
sumbyinterval = tapply(act$steps, as.factor(act$interval), sum, na.rm=T)
mediansbyinterval = tapply(act$steps, as.factor(act$interval), median, na.rm=TRUE)

hist(sumbydate)
plot(meansbydate)
plot(mediansbydate)
nas = act[is.na(act$steps),]
hist(nas$interval)
hist(nas$date, breaks=61)
```

## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
